version: '3.8'
services:
  web:
    build: .
    container_name: resume_web
    ports:
      - '3000:80'
    environment:
      - NODE_ENV=production
    env_file:
      - .env.local
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'http://localhost/']
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
