name: Auto Merge Pull Requests

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'sozdursun'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Merge Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          PR_NUMBER=$(jq --raw-output .number "$GITHUB_EVENT_PATH")
          gh pr merge $PR_NUMBER --merge --admin
