name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  # Job 1: Stop the server and fetch the latest code
  stop_server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Stop the server and fetch the latest code
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            TARGET_DIR="repo/resume"
            cd ~ || exit 1
            cd $TARGET_DIR || exit 1
            export PATH=/root/.nvm/versions/node/v21.6.2/bin:$PATH
            nvm alias default 21
            pm2 stop serhatozdursun_website || true
            PID=$(sudo netstat -tulnp | grep :3000 | awk '{print $7}' | cut -d'/' -f1)
            if [ -n "$PID" ]; then
              sudo kill -9 $PID
            fi
            rm -rf .next || true
            git pull origin main || exit 1

  # Job 2: Build the app
  build:
    runs-on: ubuntu-latest
    needs: stop_server
    if: always() # Ensure this job runs regardless of the result of stop_server
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build the app
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            TARGET_DIR="repo/resume"
            cd ~ || exit 1
            cd $TARGET_DIR || exit 1
            export PATH=/root/.nvm/versions/node/v23.6.0/bin:$PATH
            if yarn install; then
              echo "Dependencies installed successfully."
            else
              echo "Failed to install dependencies."
              exit 1
            fi
            if yarn build; then
              echo "App built successfully."
            else
              echo "Failed to build the app."
              exit 1
            fi

  # Job 3: Start the server
  start_the_server:
    runs-on: ubuntu-latest
    needs: build
    if: always() # Ensure this job runs regardless of the result of build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start the app
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export PATH=/root/.nvm/versions/node/v21.6.2/bin:$PATH
            TARGET_DIR="repo/resume"
            cd ~ || exit 1
            cd $TARGET_DIR || exit 1
            if pm2 start yarn --name "serhatozdursun_website" -- start; then
              echo "PM2 process 'serhatozdursun_website' started successfully."
            else
              echo "Failed to start the pm2 process."
              exit 1
            fi
            if pm2 save; then
              echo "PM2 process list saved successfully."
            else
              echo "Failed to save the PM2 process list."
              exit 1
            fi