name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.REPO_PATH }} || exit 1 # Navigate to the correct directory
            pm2 stop my-app || true # Stop the app managed by pm2
            git pull origin main # Pull the latest code from the main branch
            yarn install # Install any new dependencies
            yarn build # Build the app
            pm2 start yarn --name "my-app" -- start # Start the app with pm2
            pm2 save # Save the pm2 process list