name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.6.2'  # Set to the Node.js version used on your server

      - name: Install dependencies
        run: |
          yarn install

      - name: Build the app
        run: |
          rm -rf .next
          yarn build

      - name: Stop and Start Application with PM2
        run: |
          cd repo/resume || exit 1
          export PATH=$PATH:/root/.nvm/versions/node/v21.6.2/bin
          pm2 stop serhatozdursun_website || true
          pm2 delete serhatozdursun_website || true
          pm2 start yarn --name "serhatozdursun_website" -- start
          pm2 save

      - name: Print Node.js version for debugging
        run: node -v

      - name: Print PM2 version for debugging
        run: pm2 -v