name: UI_TEST

on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - 'public/**'
      - '.github/workflows/ci.yml'
      - '.github/'

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout resume repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies and build
        run: |
          yarn install
          yarn build

      - name: Start the application
        run: |
          yarn start &
        env:
          PORT: 3000

      - name: Wait for the application to be up
        run: |
          sleep 30

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Chrome
        run: |
          sudo apt update
          sudo apt install -y wget gnupg
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - name: Install ChromeDriver
        run: |
          CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          wget https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Clone the test repository
        run: |
          git clone git@github.com:serhatozdursun/serhatozdursun-ui-tests.git
        env:
          GITHUB_TOKEN: ${{ secrets.UI_TEST_TOKEN}}

      - name: Install Python dependencies
        working-directory: serhatozdursun-ui-tests
        run: |
          pip install -r requirements.txt

      - name: Run tests
        working-directory: serhatozdursun-ui-tests
        run: |
          pytest --browser chrome --base_url http://localhost:3000 --html=reports/report.html --junitxml=reports/report.xml

      - name: Upload HTML report
        uses: actions/upload-artifact@v3
        with:
          name: html-report
          path: serhatozdursun-ui-tests/reports/report.html

      - name: Upload XML report
        uses: actions/upload-artifact@v3
        with:
          name: xml-report
          path: serhatozdursun-ui-tests/reports/report.xml